import { criarCatalogoRouter } from './catalogFactory.js';
const DISPOSITIVOS_PADRAO = [
  ['AOC Roku TV', ''],
  ['Android', ''],
  ['Android TV', ''],
  ['Apple TV', ''],
  ['Chromecast', ''],
  ['Chromecast com Google TV', ''],
  ['Fire TV Cube', ''],
  ['Fire TV Stick', ''],
  ['Google TV', ''],
  ['LG webOS', ''],
  ['Linux PC', ''],
  ['MXQ Pro', ''],
  ['MacBook', ''],
  ['Nintendo Switch', ''],
  ['Notebook Windows', ''],
  ['PC Windows', ''],
  ['PS4', ''],
  ['PS5', ''],
  ['Philips Roku TV', ''],
  ['Roku Express', ''],
  ['Roku Premiere', ''],
  ['Roku Stick', ''],
  ['Roku TV', ''],
  ['Samsung Galaxy Tab', ''],
  ['Samsung Tizen', ''],
  ['Smart TV AOC', ''],
  ['Smart TV JVC', ''],
  ['Smart TV LG', ''],
  ['Smart TV Multilaser', ''],
  ['Smart TV Panasonic', ''],
  ['Smart TV Philco', ''],
  ['Smart TV Philips', ''],
  ['Smart TV Samsung', ''],
  ['Smart TV Semp TCL', ''],
  ['Smart TV Sony', ''],
  ['Smart TV TCL', ''],
  ['Smart TV Toshiba', ''],
  ['TCL Roku TV', ''],
  ['TV Box Android', ''],
  ['Tablet Android', ''],
  ['Xbox One', ''],
  ['Xbox Series S', ''],
  ['Xbox Series X', ''],
  ['Xiaomi Mi Box', ''],
  ['Xiaomi Mi TV Stick', ''],
  ['iMac', ''],
  ['iPad', ''],
  ['iPhone', ''],
];
export const dispositivosRouter = criarCatalogoRouter({
  singular: 'dispositivo',
  plural: 'dispositivos',
  titulo: 'Dispositivos',
  subtitulo: 'Gerencie o catálogo de dispositivos dos clientes',
  padroes: DISPOSITIVOS_PADRAO,
});
